services:
    sonata.admin.product:
        class: EasySlam\ProductBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Product" }
        arguments:
            - ~
            - EasySlam\ProductBundle\Entity\Product
            - ~
        calls:
            - [ setTranslationDomain, [EasySlamProductBundle]]

    sonata.admin.variantecategory:
        class: EasySlam\ProductBundle\Admin\VarianteCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Variante", label: "Variante Category" }
        arguments:
            - ~
            - EasySlam\ProductBundle\Entity\VarianteCategory
            - ~
        calls:
            - [ setTranslationDomain, [EasySlamProductBundle]]

    sonata.admin.variantecolor:
        class: EasySlam\ProductBundle\Admin\VarianteColorAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Variante", label: "Variante Color" }
        arguments:
            - ~
            - EasySlam\ProductBundle\Entity\VarianteColor
            - ~
        calls:
            - [ setTranslationDomain, [EasySlamProductBundle]]

    sonata.admin.variantetype:
        class: EasySlam\ProductBundle\Admin\VarianteTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Variante", label: "Variante Type" }
        arguments:
            - ~
            - EasySlam\ProductBundle\Entity\VarianteType
            - ~
        calls:
            - [ setTranslationDomain, [EasySlamProductBundle]]

    sonata.admin.etatcommand:
        class: EasySlam\ProductBundle\Admin\EtatCommandAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Variante", label: "Ã‰tat des commandes" }
        arguments:
            - ~
            - EasySlam\ProductBundle\Entity\EtatCommand
            - ~
        calls:
            - [ setTranslationDomain, [EasySlamProductBundle]]

    sonata.admin.commands:
        class: EasySlam\ProductBundle\Admin\CommandAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Gestion des commandes" }
        arguments:
            - ~
            - EasySlam\ProductBundle\Entity\Commands
            - ~
        calls:
            - [ setTranslationDomain, [EasySlamProductBundle]]

    sonata.admin.detailscommands:
        class: EasySlam\ProductBundle\Admin\DetailsCommandAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Gestion des commandes" }
        arguments:
            - ~
            - EasySlam\ProductBundle\Entity\DetailsCommand
            - ~
        calls:
            - [ setTranslationDomain, [EasySlamProductBundle]]

    sonata.admin.demande:
        class: EasySlam\ProductBundle\Admin\DemandeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Gestion des stocks" }
        arguments:
            - ~
            - EasySlam\ProductBundle\Entity\Demande
            - ~
        calls:
            - [ setTranslationDomain, [EasySlamProductBundle]]
